### ISSUE TITLE
[Refactor] 롤업 설정 변경

### ISSUE THREAD

**Issue by ghdtjgus76** [gdg-hongik-univ/wow-design-system#10]
## 🎯 설명
롤업 설정 중 개선하면 좋을 것 같은 부분이 생겨 아래 사항들을 변경하려 합니다.

## ✅ TODO
- [x] preserveModules 옵션 대신 entry file을 배열로 전달
https://github.com/GDSC-Hongik/wow-design-system/pull/4#issuecomment-2102153249
- [x] external로 설정할 dependency가 있다면 변경
- [x] import문에서 확장자를 명시하지 않았을 때 롤업에서도 성능 관련 문제가 있는지 확인, 있다면 관련 설정 변경
https://ko.vitejs.dev/guide/performance.html#reduce-resolve-operations
