### ISSUE TITLE
[Chore] Picker 컴포넌트 QA사항 반영

### ISSUE THREAD

**Issue by hamo-o** [gdg-hongik-univ/wow-design-system#156]
## ✅ TODO
- [x] 초기값 00시인 경우
- [x] `disabled` 상태 스타일 추가
- [x] [드롭다운 옵션 정렬](https://www.notion.so/QA-a14c81246ee24c6cb948577978cfbcb5?pvs=4)
