### ISSUE TITLE
[Bug] wow-ui 에서 빌드하면 alias 경로 인식 못하는 문제

### ISSUE THREAD

**Issue by SeieunYoo** [gdg-hongik-univ/wow-design-system#37]
## 🎯 설명
- @ alias 경로를 인식하지 못해서 빌드한 wow-ui 컴포넌트의 import 문이 인식 안되는 문제
- types,hooks,utils 에서 공통으로 발생하는 것으로 추정,,,
- 상대경로로 설정해서 해결해두었지만 제대로 된 해결 필요,,
## ✅ TODO
- [x] tsc-alias 설정 적용
- [x] wow-icons 스크립트 변경
- [x] 기존 상대 경로로 사용하던 import문 절대 경로로 변경
