### ISSUE TITLE
[Refactor] Button, TextButton 컴포넌트 리팩토링

### ISSUE THREAD

**Issue by hamo-o** [gdg-hongik-univ/wow-design-system#69]
## 🎯 설명
`BaseButton` 컴포넌트를 생성하고 `Button`과 `TextButton`의 공통 로직을 처리합니다.

## ✅ TODO
- [ ] https://github.com/GDSC-Hongik/wow-design-system/pull/62#discussion_r1660215127 `BaseButton` 컴포넌트 생성
- [ ] https://github.com/GDSC-Hongik/wow-design-system/pull/62#discussion_r1660213353 `Button`, `TextButton` 공통 타입 분리
- [ ] https://github.com/GDSC-Hongik/wow-design-system/pull/62#discussion_r1649561611 `BasicButtonProps` 고려하기
- [ ] `disabled` 스타일 변경사항 반영 https://www.figma.com/design/OyL8TwVvhHHcR82AtOeEdv?node-id=556-1101#865726917
